### ISSUE TITLE
Keycloak OIDC not supported 

### ISSUE THREAD

**Issue by b-d-e** [wandb/server#142]
Version: [wandb/local:0.58.1](https://hub.docker.com/layers/wandb/local/0.58.1/images/sha256-12c1ba5718bf36fbe277e63fd30917304eaa1402d962fea137e3b3ca2a561fe6?context=explore)

I'm trying to configure a local instance of wandb to use [Keycloak](https://www.keycloak.org/) as an OIDC provider, but struggling to get it to work either through the web admin settings or by setting docker enviroment variables.

I believe it's because of the way keycloak uses 'realms' - so where most OIDC providers will use a URL of the schema `https://{DOMAIN}/users/sign_in` keycloak uses something like `https://{DOMAIN}/realms/{REALM_NAME}/protocol/openid-connect/auth?client_id={CLIENT_ID}`.

Other OIDC clients (e.g. [Outline](https://github.com/outline/outline)) allow more expressive docker environment variables which work with Keycloak, e.g:
```
OIDC_AUTH_URI=https://{DOMAIN}/realms/{REALM_NAME}/protocol/openid-connect/auth
OIDC_TOKEN_URI=https://{DOMAIN}/realms/{REALM_NAME}/protocol/openid-connect/token
OIDC_USERINFO_URI=https://{DOMAIN}/realms/{REALM_NAME}/protocol/openid-connect/userinfo
```

but setting these for wandb causes the gorilla service to panic as it cannot locate the URL:
```
{"level":"INFO","time":"2024-09-07T15:44:41.254942969Z","info":{"program":"gorilla","source":"github.com/wandb/core/services/gorilla/cmd/gorilla.go:1409","pid":1583},"data":{"dd.service":"gorilla","dd.version":"18d22e645275697ba614e1d1ea139452c4bed39f"},"message":"parsed schema","dd.trace_id":""}
panic: Get "https://{DOMAIN}/users/sign_in": stopped after 10 redirects

goroutine 1 [running]:
github.com/wandb/core/services/gorilla/cmd.(*gorillaCommander).MainCmd(0xc00188db00, {0xc00188dbe0, 0x1, 0x1})
        /home/circleci/go/src/github.com/wandb/core/services/gorilla/cmd/gorilla.go:1528 +0xccb6
main.main()
        /home/circleci/go/src/github.com/wandb/core/services/gorilla/cmd/megabinary/main.go:75 +0x431
```

Apologies if this _is_ implemented and I am missing it in the docs, but am struggling to find anything.

**Comment by b-d-e** [comment]
Hi Bonnie,

Thanks for getting back to me - glad to see there are resources available
to help!
Sorry but I'm not seeing a link or any attachments here - could you please
resend?

Thanks,
Benjamin

**Comment by boshwandb** [comment]
Hi @b-d-e !
It seemed like my link didn't get carried over from my backend. I'm attaching it [here](https://github.com/wandb/sa-team-solutions/blob/main/knowledge-base/keycloack-sso-oidc-pkce.md) directly in the comment. Sorry for the inconvenience.

**Comment by b-d-e** [comment]
Is that a private repo? I'm getting 404.

**Comment by boshwandb** [comment]
I apologize, it is currently a private repo. Let me list the instructions here in the next comment. Your patience is greatly appreciated.

**Comment by boshwandb** [comment]
## Keycloak Configuration

1. Create Keycloak ream

This is optional and you can use the master realm, but it's highly recommended to work with realms.
<img width="1827" alt="01 - create realm" src="https://github.com/user-attachments/assets/e0a543dc-aef6-4d4e-966d-b5f05fbc2e77">
1. Create and Configure Client

:warning: Replace all the values with valid values for your organization.

Next step after create the realm, is setup the `client`, which is the configuration to be used by the application that will authenticate with Keycloak.

The client type myst be `OpenID Connect`

- Create client

<img width="1754" alt="02 - configure client 1" src="https://github.com/user-attachments/assets/0ab2487b-7f60-4380-9132-ce998978f58c">

- Configure the client

<img width="1519" alt="02 - configure client 2" src="https://github.com/user-attachments/assets/3aaff9af-2e57-47d8-b471-850b55487f37">

Keep the `Standard flow` and the `Implicit flow` enabled.

- Set W&B URL's

<img width="1759" alt="02 - configure client 3" src="https://github.com/user-attachments/assets/92d36ad0-984f-44e7-9b41-e3906ea2bf12">

For this configuration, the most important URL is the `Valid redirect URLs`.
This is the callback URL that Keycloak will call to send W&B the authentication token.

1. Configure OIDC Scope

When the client type `OpenID Connect` is created, Keycloak already set a default OIDC scope that contain all required claims. However, some Keycloak configuration may set different claims for OIDC scopes.
For W&B, one of the most important claims is the `email`, so regarldess the scop you will use, ensure the claims `email` and `profile`are set to `Default`

<img width="1849" alt="03 - configure client scope" src="https://github.com/user-attachments/assets/fe1e417a-cd6c-456c-a18d-330bbd530c0c">

1. Enable PKCE

Still in the client configuration, navigate to the `Advanced` tab and click on `Advanced Settings`

<img width="1704" alt="04 - configure PKCE" src="https://github.com/user-attachments/assets/893ad296-a36c-4aa1-80ba-5ac96742bc24">

Search for the drop down menu `Proof key code exchange` and select `S256`

<img width="1017" alt="04 - configure PKCE detail" src="https://github.com/user-attachments/assets/193cfd0e-6132-46fb-a546-94665256f45f">

Save the configuration.

1. Add user and/or groups

Now the next step is assign users and/or groups to the newly created realm to allow users authenticate using the also newly created `wandb` client.

## W&B Configuration

The W&B configuration will depend on how did you installed the platform. For this guide, I will cover the configuration using the [W&B helm chart](https://github.com/wandb/helm-charts/blob/main/charts/wandb/values.yaml#L70-L79) and the configuration via W&B Operator console.

- Helm Cart

As highlighted in the above link, you will need to add the Keycloak configuration according to the example below in the `values.yaml` you used to install W&B.

```yaml
sso:
  enabled: true
  # Automatically provision a user if SSO auth succeeds
  autoProvision: true
  clientId: wandb
  issuer: http://keycloak.home.lab/realms/wandb/
  # Can be implicit or pkce
  method: pkce
```

Once the `values.yaml` is configured, apply the new configuration and test it.

- Operator Console

Navigate to `https://<WANDB FQDN>/console/settings/auth` and input Keycloak data.

<img width="1583" alt="operator-console" src="https://github.com/user-attachments/assets/3c69b255-4205-46ad-a788-cf556101b41d">

## Login Screens

W&B Login

<img width="2290" alt="07 - wandb login screen " src="https://github.com/user-attachments/assets/37b48d93-c4fd-47bc-96ea-6a6b576f6137">

Login redirected to Keycloak for Authentication

<img width="990" alt="08 - keycloak login screen " src="https://github.com/user-attachments/assets/e4377d51-b697-4025-b7cc-5403b575ea47">

In case the Keycloak user is also new, it may need to change the password depending how Keycloak is configured

<img width="1009" alt="09 - keycloak change password" src="https://github.com/user-attachments/assets/d0d01d94-284d-4dc2-a732-67f3c0a2b0f3">

After SSO authentication, user is created in W&B

<img width="2194" alt="10 - user provisioning wandb" src="https://github.com/user-attachments/assets/28047236-fccf-4e6b-a371-b865188cc353">

Login is complete

<img width="2275" alt="11 - user logged in" src="https://github.com/user-attachments/assets/dabb7fdd-1732-49fc-942c-aac1b235f55b">

**Comment by b-d-e** [comment]
Hi Bonnie. I have had a quick look (on docker, not with helm), though was hitting another issue - but I think that might be an networking issue my end. 
Do you have a comprehensive list of the environment variables a docker instance of`wandb/local` takes? There's [this list](https://docs.wandb.ai/guides/hosting/env-vars), but that isn't exhaustive (e.g. there's some GORILLA vars that aren't in there)

**Comment by boshwandb** [comment]
Hi Benjamin! Does [this](https://docs.wandb.ai/guides/hosting/iam/advanced_env_vars) one help?
